(function(){
"use strict";
const $=id=>document.getElementById(id), registry=window.SimpleAdvEventRegistry, validator=window.SimpleAdvValidator;
const ui={file:$('file-input'),scenes:$('scene-list'),commands:$('command-list'),empty:$('empty-state'),sceneTitle:$('scene-title'),sceneCaption:$('scene-caption'),form:$('command-form'),work:$('work-form'),title:$('title-form'),assets:$('asset-editor'),preview:$('preview'),previewStatus:$('preview-status'),saveStatus:$('save-status'),issueCount:$('issue-count'),issueList:$('issue-list'),issues:$('issues-dialog'),confirm:$('confirm-dialog')};
const typeLabels={message:'メッセージ',background:'背景',character:'立ち絵表示',characterHide:'立ち絵非表示',choice:'選択肢',set:'変数代入',add:'数値加算',branch:'条件分岐',jump:'シーン移動',bgm:'BGM',bgmStop:'BGM停止',se:'SE',event:'固有イベント',end:'終了'};
let data=null,sceneId=null,commandIndex=-1,issues=[],dirty=false,saveTimer=0,currentWork=null,serverMode=false,scriptDraft=null;
const clone=value=>JSON.parse(JSON.stringify(value));
function escapeHtml(value){return String(value??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function draftKey(){return `simple-adv-editor:draft:${currentWork||'imported'}`;}
function markDirty(){dirty=true;ui.saveStatus.textContent='編集中…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(draftKey(),JSON.stringify(data));ui.saveStatus.textContent='未保存の下書きを保持しています';}catch{ui.saveStatus.textContent='下書きを保存できません';}validateData(false);},350);}
function currentCommands(){return data&&sceneId?data.scenes[sceneId]:null;}
function sceneIds(){return data?Object.keys(data.scenes):[];}
function variableIds(type){return data?Object.keys(data.variables).filter(id=>typeof data.variables[id]===type):[];}
function assetIds(group){return data?Object.keys(data.assets[group]||{}):[];}
function allCharacterIds(){return [...assetIds('characters'),...assetIds('enemies')];}
function options(values,selected){return values.map(v=>`<option value="${escapeHtml(v)}"${v===selected?' selected':''}>${escapeHtml(v)}</option>`).join('');}
function field(label,name,value,type='text',extra=''){return `<div class="field"><label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${escapeHtml(value)}" ${extra}></div>`;}
function selectField(label,name,values,value){return `<div class="field"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${options(values,value)}</select></div>`;}
function textareaField(label,name,value){return `<div class="field"><label for="f-${name}">${label}</label><textarea id="f-${name}" name="${name}">${escapeHtml(value)}</textarea></div>`;}
function resetSelection(){commandIndex=-1;renderCommands();renderForm();renderPreview();}

function parseScript(source){const lines=source.replace(/\r\n?/g,'\n').split('\n'),scenes={},errors=[];let current=null,index=0;const add=command=>{if(!current)errors.push(`行${index+1}: 先に「# scene_id」が必要です。`);else scenes[current].push(command);};while(index<lines.length){const raw=lines[index],line=raw.trim();if(!line){index++;continue;}const header=line.match(/^#\s+([A-Za-z][A-Za-z0-9_]*)\s*$/);if(header){current=header[1];if(scenes[current])errors.push(`行${index+1}: シーン「${current}」が重複しています。`);else scenes[current]=[];index++;continue;}if(line.startsWith('#')){errors.push(`行${index+1}: シーン見出しは「# scene_id」で記述してください。`);index++;continue;}if(line.startsWith('@')){const parts=line.split(/\s+/),tag=parts[0].slice(1);if(tag==='background'&&parts.length===2)add({type:'background',asset:parts[1]});else if(tag==='character'&&parts.length===3&&['left','center','right'].includes(parts[1]))add({type:'character',slot:parts[1],asset:parts[2]});else if(tag==='hide'&&parts.length===2&&['left','center','right'].includes(parts[1]))add({type:'characterHide',slot:parts[1]});else if(tag==='jump'&&parts.length===2)add({type:'jump',scene:parts[1]});else if(tag==='end')add({type:'end',message:line.slice(4).trim()||'おしまい'});else errors.push(`行${index+1}: 未対応または引数が不正なタグ「${line}」です。`);index++;continue;}const paragraph=[];const start=index;while(index<lines.length&&lines[index].trim()&&!lines[index].trim().startsWith('#')&&!lines[index].trim().startsWith('@'))paragraph.push(lines[index++]);const speakerMatch=paragraph[0]?.trim().match(/^(.+?)[：:]$/);const speaker=speakerMatch?speakerMatch[1]:'';const text=(speakerMatch?paragraph.slice(1):paragraph).join('\n').trim();if(!text)errors.push(`行${start+1}: メッセージ本文がありません。`);else add({type:'message',speaker,text});}if(!Object.keys(scenes).length)errors.push('シーンがありません。「# opening」のような見出しを追加してください。');Object.entries(scenes).forEach(([id,commands])=>{commands.forEach(command=>{if(command.type==='background'&&!data.assets.backgrounds[command.asset])errors.push(`${id}: 背景素材「${command.asset}」が未登録です。`);if(command.type==='character'&&!data.assets.characters[command.asset]&&!data.assets.enemies[command.asset])errors.push(`${id}: 立ち絵・敵素材「${command.asset}」が未登録です。`);if(command.type==='jump'&&!scenes[command.scene]&&!data.scenes[command.scene])errors.push(`${id}: 移動先シーン「${command.scene}」がありません。`);});});return{scenes,errors};}
function previewScript(){scriptDraft=parseScript($('script-source').value);Object.entries(scriptDraft.scenes).forEach(([id,commands])=>{if(!commands.length)scriptDraft.errors.push(`${id}: 命令がありません。`);if($('script-mode').value==='replace-all')commands.filter(c=>c.type==='jump'&&!scriptDraft.scenes[c.scene]).forEach(c=>scriptDraft.errors.push(`${id}: 全置換後に移動先「${c.scene}」が存在しません。`));});$('script-errors').textContent=[...new Set(scriptDraft.errors)].join('\n');$('script-preview').textContent=JSON.stringify(scriptDraft.scenes,null,2);$('apply-script').disabled=Boolean(scriptDraft.errors.length);}
function applyScript(){if(!scriptDraft||scriptDraft.errors.length)return;const imported=clone(scriptDraft.scenes),mode=$('script-mode').value;if(mode==='replace-all')data.scenes=imported;else Object.entries(imported).forEach(([id,commands])=>{if(mode==='new-only'){if(!data.scenes[id])data.scenes[id]=commands;}else if(mode==='replace-matching')data.scenes[id]=commands;else if(mode==='append'){if(!data.scenes[id])data.scenes[id]=commands;else{const target=data.scenes[id],end=target.at(-1)?.type==='end'?target.pop():null;target.push(...commands);if(end)target.push(end);}}});if(!data.scenes[data.game.startScene])data.game.startScene=Object.keys(data.scenes)[0];sceneId=Object.keys(imported)[0]||data.game.startScene;commandIndex=-1;markDirty();renderAll();$('script-dialog').close();ui.saveStatus.textContent='シナリオを反映しました。内容を確認して作品へ保存してください。';}
async function createNewWork(event){event.preventDefault();const id=$('new-work-id').value.trim(),title=$('new-work-title').value.trim();if(!/^[A-Za-z][A-Za-z0-9_-]*$/.test(id))return alert('作品IDは半角英字で始め、半角英数字・_・-で指定してください。');try{await apiRequest('/api/works',{method:'POST',body:JSON.stringify({id,title})});currentWork=id;$('new-work-dialog').close();$('new-work-form').reset();await connectServer();ui.saveStatus.textContent=`新しい作品「${title}」を作成しました`;}catch(error){alert(`作品を作成できません: ${error.message}`);}}

async function loadSample(){try{currentWork='sansu-quest';const response=await fetch('../works/sansu-quest/game.json',{cache:'no-store'});if(!response.ok)throw Error(`HTTP ${response.status}`);loadData(await response.json(),'さんすうクエスト');}catch(error){setIssues([`読み込みに失敗しました: ${error.message}`]);ui.issues.showModal();}}
function loadData(next,label){if(!next||typeof next!=='object'||Array.isArray(next))throw Error('JSONのルートがオブジェクトではありません');data=clone(next);sceneId=data.game?.startScene&&data.scenes?.[data.game.startScene]?data.game.startScene:Object.keys(data.scenes||{})[0]||null;commandIndex=-1;dirty=false;ui.saveStatus.textContent=`${label}を読み込みました`;renderAll();validateData(false);}
function renderAll(){renderScenes();renderCommands();renderForm();renderWork();renderTitle();renderAssets();renderPreview();}
function sceneReferences(target){if(!data||!target)return[];const refs=[];if(data.game.startScene===target)refs.push('開始シーン');Object.entries(data.scenes).forEach(([from,commands])=>commands.forEach((c,index)=>{if(c.scene===target)refs.push(`${from} #${index+1}`);if(c.then===target)refs.push(`${from} #${index+1} 成立時`);if(c.else===target)refs.push(`${from} #${index+1} 不成立時`);(c.options||[]).forEach((o,n)=>{if(o.scene===target)refs.push(`${from} #${index+1} 選択肢${n+1}`);});}));return refs;}
function renderScenes(){ui.scenes.replaceChildren();if(!data)return;sceneIds().forEach(id=>{const b=document.createElement('button');b.type='button';b.className=`scene-button${id===sceneId?' active':''}`;const name=document.createElement('strong');name.textContent=id;const count=document.createElement('span');count.textContent=`${data.scenes[id].length}命令`;b.append(name,count);b.addEventListener('click',()=>{sceneId=id;resetSelection();renderScenes();});ui.scenes.append(b);});const refs=sceneReferences(sceneId);$('scene-references').textContent=`参照元：${refs.length?refs.join('、'):'なし'}`;}
function summary(c){switch(c.type){case'message':return `${c.speaker?c.speaker+'：':''}${c.text}`;case'background':return c.asset;case'character':return `${c.slot} ← ${c.asset}`;case'characterHide':return c.slot;case'jump':return `→ ${c.scene}`;case'branch':return `${c.condition?.variable} ${c.condition?.operator} ${c.condition?.value} ? ${c.then} : ${c.else}`;case'choice':return (c.options||[]).map(x=>`${x.text} → ${x.scene}`).join('\n');case'event':return `${c.event}（${c.args?.questionCount??'?'}問）`;case'set':return `${c.variable} = ${c.value}`;case'add':return `${c.variable} += ${c.fromVariable??c.value}`;case'bgm':case'se':return c.asset;case'bgmStop':return'再生中のBGMを停止';case'end':return c.message||'おしまい';default:return JSON.stringify(c);}}
function renderCommands(){ui.commands.replaceChildren();const commands=currentCommands();ui.empty.classList.toggle('hidden',Boolean(commands));ui.sceneTitle.textContent=sceneId||'作品を読み込んでください';ui.sceneCaption.textContent=commands?`${commands.length}個の命令`:'';if(!commands)return;commands.forEach((c,index)=>{const li=document.createElement('li');li.className=`command-card${index===commandIndex?' active':''}`;li.tabIndex=0;li.innerHTML=`<span class="command-number">${index+1}</span><span class="command-kind">${escapeHtml(typeLabels[c.type]||c.type)}</span><p class="command-summary">${escapeHtml(summary(c))}</p><div class="card-actions"><button data-action="up" title="上へ">↑</button><button data-action="down" title="下へ">↓</button><button data-action="copy">複製</button><button data-action="delete">削除</button></div>`;li.addEventListener('click',event=>{const action=event.target.dataset.action;if(action){event.stopPropagation();editCommandList(action,index);return;}commandIndex=index;renderCommands();renderForm();renderPreview();});li.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();li.click();}});ui.commands.append(li);});}
function editCommandList(action,index){const commands=currentCommands();if(action==='up'&&index>0){[commands[index-1],commands[index]]=[commands[index],commands[index-1]];commandIndex=index-1;}else if(action==='down'&&index<commands.length-1){[commands[index+1],commands[index]]=[commands[index],commands[index+1]];commandIndex=index+1;}else if(action==='copy'){commands.splice(index+1,0,clone(commands[index]));commandIndex=index+1;}else if(action==='delete'){commands.splice(index,1);commandIndex=Math.min(index,commands.length-1);}markDirty();renderCommands();renderForm();renderPreview();}
function makeCommand(type){const firstScene=sceneIds()[0]||'';const firstChar=allCharacterIds()[0]||'';const firstBg=assetIds('backgrounds')[0]||'';const firstVar=Object.keys(data.variables)[0]||'';return({message:{type,speaker:'',text:'あたらしい メッセージ'},background:{type,asset:firstBg},character:{type,slot:'left',asset:firstChar},characterHide:{type,slot:'left'},jump:{type,scene:firstScene},branch:{type,condition:{variable:firstVar,operator:'==',value:data.variables[firstVar]??false},then:firstScene,else:firstScene},choice:{type,options:[{text:'すすむ',scene:firstScene},{text:'もどる',scene:firstScene}]},event:{type,event:'multiplicationQuiz',args:{rows:[2],questionCount:2,requiredCorrect:1,presentation:{}},result:{correct:variableIds('number')[0]||'',wrong:variableIds('number')[1]||variableIds('number')[0]||'',cleared:variableIds('boolean')[0]||''}},set:{type,variable:firstVar,value:data.variables[firstVar]??false},add:{type,variable:variableIds('number')[0]||'',value:1},bgm:{type,asset:assetIds('bgm')[0]||''},bgmStop:{type},se:{type,asset:assetIds('se')[0]||''},end:{type,message:'おしまい'}})[type];}
function addCommand(){if(!currentCommands())return;const c=makeCommand($('command-type').value);currentCommands().push(c);commandIndex=currentCommands().length-1;markDirty();renderCommands();renderForm();renderPreview();}

function renderForm(){ui.form.innerHTML='';const c=currentCommands()?.[commandIndex];if(!c){ui.form.innerHTML='<p class="muted">中央の命令を選択してください。</p>';return;}let html=`<p class="badge">${escapeHtml(typeLabels[c.type]||c.type)}</p>`;switch(c.type){case'message':html+=field('話者名（省略可）','speaker',c.speaker||'')+textareaField('本文','text',c.text);break;case'background':html+=selectField('背景素材','asset',assetIds('backgrounds'),c.asset);break;case'character':html+=selectField('スロット','slot',['left','center','right'],c.slot)+selectField('立ち絵・敵素材','asset',allCharacterIds(),c.asset);break;case'characterHide':html+=selectField('スロット','slot',['left','center','right'],c.slot);break;case'jump':html+=selectField('移動先','scene',sceneIds(),c.scene);break;case'end':html+=field('終了メッセージ','message',c.message||'');break;case'bgm':html+=selectField('BGM素材','asset',assetIds('bgm'),c.asset);break;case'se':html+=selectField('SE素材','asset',assetIds('se'),c.asset);break;case'bgmStop':html+='<p class="muted">設定項目はありません。</p>';break;case'set':html+=selectField('変数','variable',Object.keys(data.variables),c.variable)+field('値','value',c.value);break;case'add':html+=selectField('数値変数','variable',variableIds('number'),c.variable)+selectField('加算方法','addMode',['固定値','別の変数'],c.fromVariable?'別の変数':'固定値')+(c.fromVariable?selectField('加算元','fromVariable',variableIds('number'),c.fromVariable):field('加算値','value',c.value,'number','step="any"'));break;case'branch':html+=selectField('条件変数','conditionVariable',Object.keys(data.variables),c.condition.variable)+selectField('比較','operator',['==','!=','>','>=','<','<='],c.condition.operator)+field('比較値','conditionValue',c.condition.value)+selectField('成立時','then',sceneIds(),c.then)+selectField('不成立時','else',sceneIds(),c.else);break;case'choice':html+='<div class="field-label">選択肢</div>'+(c.options||[]).map((o,i)=>`<div class="choice-row" data-choice="${i}">${field('表示文','choiceText',o.text)}${selectField('移動先','choiceScene',sceneIds(),o.scene)}<button class="danger small" data-remove-choice="${i}" type="button">この選択肢を削除</button></div>`).join('')+'<button id="add-choice" class="secondary" type="button">＋ 選択肢</button>';break;case'event':html+=field('イベントID','event',c.event)+field('段（カンマ区切り）','rows',(c.args.rows||[]).join(','))+field('問題数','questionCount',c.args.questionCount,'number','min="1"')+field('必要正解数','requiredCorrect',c.args.requiredCorrect,'number','min="0"')+selectField('味方カットイン','allyCutin',['',...assetIds('characters')],c.args.presentation?.allyCutin||'')+selectField('敵','enemy',['',...assetIds('enemies')],c.args.presentation?.enemy||'')+selectField('正解数の格納先','resultCorrect',variableIds('number'),c.result.correct)+selectField('不正解数の格納先','resultWrong',variableIds('number'),c.result.wrong)+selectField('合否の格納先','resultCleared',variableIds('boolean'),c.result.cleared);break;}ui.form.innerHTML=html;bindCommandForm(c);}
function parseLike(value,reference){if(typeof reference==='boolean')return value==='true';if(typeof reference==='number')return Number(value);return value;}
function bindCommandForm(c){ui.form.querySelectorAll('input,textarea,select').forEach(input=>input.addEventListener('change',()=>{const n=input.name,v=input.value;if(n==='conditionVariable'){c.condition.variable=v;c.condition.value=data.variables[v];}else if(n==='conditionValue')c.condition.value=parseLike(v,data.variables[c.condition.variable]);else if(n==='operator')c.condition.operator=v;else if(n==='then'||n==='else')c[n]=v;else if(n==='addMode'){if(v==='固定値'){delete c.fromVariable;c.value=1;}else{delete c.value;c.fromVariable=variableIds('number')[0]||'';}renderForm();}else if(n==='rows')c.args.rows=v.split(',').map(x=>Number(x.trim())).filter(Number.isFinite);else if(['questionCount','requiredCorrect'].includes(n))c.args[n]=Number(v);else if(['allyCutin','enemy'].includes(n)){c.args.presentation=c.args.presentation||{};if(v)c.args.presentation[n]=v;else delete c.args.presentation[n];}else if(n.startsWith('result'))c.result[n.replace('result','').toLowerCase()]=v;else if(n==='value')c.value=parseLike(v,data.variables[c.variable]??c.value);else if(n==='choiceText'||n==='choiceScene'){const i=Number(input.closest('[data-choice]').dataset.choice);c.options[i][n==='choiceText'?'text':'scene']=v;}else c[n]=v;markDirty();renderCommands();renderPreview();}));const add=$('add-choice');if(add)add.addEventListener('click',()=>{c.options.push({text:'あたらしい選択肢',scene:sceneIds()[0]||''});markDirty();renderForm();renderCommands();});ui.form.querySelectorAll('[data-remove-choice]').forEach(b=>b.addEventListener('click',()=>{if(c.options.length<=2)return alert('選択肢は2件以上必要です。');c.options.splice(Number(b.dataset.removeChoice),1);markDirty();renderForm();renderCommands();}));}

function renderWork(){if(!data){ui.work.innerHTML='';return;}ui.work.innerHTML=field('作品ID','id',data.game.id)+field('リビジョン','revision',data.game.revision,'number','min="1"')+field('タイトル','title',data.game.title)+selectField('開始シーン','startScene',sceneIds(),data.game.startScene);ui.work.querySelectorAll('input,select').forEach(input=>input.addEventListener('change',()=>{data.game[input.name]=input.name==='revision'?Number(input.value):input.value;markDirty();}));}
function renderTitle(){if(!data){ui.title.innerHTML='';return;}const title=data.game.titleScreen;if(!title){ui.title.innerHTML='<p class="muted">この作品は旧形式のため、起動時に直接シナリオを開始します。</p><button id="enable-title" type="button">タイトル画面を有効にする</button>';$('enable-title').addEventListener('click',()=>{data.formatVersion=2;data.game.titleScreen={background:assetIds('backgrounds')[0]||'',newGameLabel:'はじめから',continueLabel:'つづきから'};markDirty();renderTitle();});return;}ui.title.innerHTML=selectField('タイトル画像（背景素材）','background',assetIds('backgrounds'),title.background)+field('新規開始ボタン','newGameLabel',title.newGameLabel)+field('再開ボタン','continueLabel',title.continueLabel)+'<p class="muted">「つづきから」は、この作品の有効なセーブがある場合だけ選べます。</p>';ui.title.querySelectorAll('input,select').forEach(input=>input.addEventListener('change',()=>{title[input.name]=input.value;markDirty();}));}
function renderAssets(){ui.assets.replaceChildren();if(!data)return;['backgrounds','characters','enemies','bgm','se'].forEach(group=>{const section=document.createElement('section');section.className='asset-group';section.innerHTML=`<div class="panel-heading"><h3>${group}</h3><button class="small secondary" data-add-asset="${group}" type="button">＋</button></div>`;Object.entries(data.assets[group]).forEach(([id,path])=>{const row=document.createElement('div');row.className='asset-row';row.innerHTML=`<input aria-label="素材ID" value="${escapeHtml(id)}"><input aria-label="素材パス" value="${escapeHtml(path)}"><button class="small danger" type="button">削除</button>`;const inputs=row.querySelectorAll('input');inputs[0].addEventListener('change',()=>renameAsset(group,id,inputs[0].value));inputs[1].addEventListener('change',()=>{data.assets[group][id]=inputs[1].value;markDirty();renderPreview();});row.querySelector('button').addEventListener('click',()=>{delete data.assets[group][id];markDirty();renderAssets();});section.append(row);});section.querySelector('[data-add-asset]').addEventListener('click',()=>{let id='new_asset',n=2;while(data.assets[group][id])id=`new_asset_${n++}`;data.assets[group][id]='assets/path/file.png';markDirty();renderAssets();});ui.assets.append(section);});}
function renameAsset(group,oldId,newId){if(!/^[A-Za-z][A-Za-z0-9_]*$/.test(newId)||data.assets[group][newId]){alert('素材IDが不正、または重複しています。');renderAssets();return;}data.assets[group][newId]=data.assets[group][oldId];delete data.assets[group][oldId];Object.values(data.scenes).flat().forEach(c=>{if(c.asset===oldId)c.asset=newId;if(c.args?.presentation?.allyCutin===oldId)c.args.presentation.allyCutin=newId;if(c.args?.presentation?.enemy===oldId)c.args.presentation.enemy=newId;});markDirty();renderAll();}

function rebuildSceneOrder(ids){const rebuilt={};ids.forEach(id=>{rebuilt[id]=data.scenes[id];});data.scenes=rebuilt;}
function addScene(){if(!data)return;let id='new_scene',n=2;while(data.scenes[id])id=`new_scene_${n++}`;const ids=sceneIds(),selectedIndex=sceneId?ids.indexOf(sceneId):-1;data.scenes[id]=[{type:'end',message:'おしまい'}];const nextOrder=sceneId?[...ids.slice(0,selectedIndex+1),id,...ids.slice(selectedIndex+1)]:[...ids,id];rebuildSceneOrder(nextOrder);sceneId=id;commandIndex=0;markDirty();renderAll();}
function moveScene(offset){if(!sceneId)return;const ids=sceneIds(),from=ids.indexOf(sceneId),to=from+offset;if(to<0||to>=ids.length)return;[ids[from],ids[to]]=[ids[to],ids[from]];rebuildSceneOrder(ids);markDirty();renderAll();}
function renameScene(){if(!sceneId)return;const next=prompt('新しいシーンIDを入力してください。',sceneId);if(!next||next===sceneId)return;if(!/^[A-Za-z][A-Za-z0-9_]*$/.test(next)||data.scenes[next])return alert('シーンIDが不正、または重複しています。');const old=sceneId,rebuilt={};Object.entries(data.scenes).forEach(([id,commands])=>{rebuilt[id===old?next:id]=commands;});data.scenes=rebuilt;if(data.game.startScene===old)data.game.startScene=next;Object.values(data.scenes).flat().forEach(c=>{if(c.scene===old)c.scene=next;if(c.then===old)c.then=next;if(c.else===old)c.else=next;(c.options||[]).forEach(o=>{if(o.scene===old)o.scene=next;});});sceneId=next;markDirty();renderAll();}
function deleteScene(){if(!sceneId||sceneIds().length<=1)return alert('シーンは1件以上必要です。');const refs=sceneReferences(sceneId),warning=refs.length?`\n\n参照元が ${refs.length}件あります。削除後に検証エラーを修正してください。`:'';if(!confirm(`シーン「${sceneId}」を削除しますか？${warning}`))return;const removed=sceneId;delete data.scenes[removed];sceneId=sceneIds()[0];if(data.game.startScene===removed)data.game.startScene=sceneId;commandIndex=-1;markDirty();renderAll();}
function renderPreview(){ui.preview.replaceChildren();ui.preview.style.backgroundImage='none';const commands=currentCommands();if(!commands||commandIndex<0){ui.preview.innerHTML='<p>命令を選ぶと、背景・立ち絵・メッセージの状態を確認できます。</p>';ui.previewStatus.textContent='未選択';return;}const state={background:null,slots:{left:null,center:null,right:null},message:null};commands.slice(0,commandIndex+1).forEach(c=>{if(c.type==='background')state.background=c.asset;if(c.type==='character')state.slots[c.slot]=c.asset;if(c.type==='characterHide')state.slots[c.slot]=null;if(c.type==='message')state.message=c;});if(state.background&&data.assets.backgrounds[state.background])ui.preview.style.backgroundImage=`url("../works/sansu-quest/${data.assets.backgrounds[state.background]}")`;Object.entries(state.slots).forEach(([slot,id])=>{if(!id)return;const path=data.assets.characters[id]||data.assets.enemies[id];if(!path)return;const img=document.createElement('img');img.className=`preview-character ${slot}`;img.src=`../works/sansu-quest/${path}`;img.alt=id;ui.preview.append(img);});const p=document.createElement('p');p.textContent=state.message?`${state.message.speaker?state.message.speaker+'：\n':''}${state.message.text}`:summary(commands[commandIndex]);ui.preview.append(p);ui.previewStatus.textContent=`${commandIndex+1} / ${commands.length}`;}

function validateData(show=true){if(!data)return;try{validator.validate(clone(data),registry);setIssues([]);}catch(error){setIssues([error.message]);}if(show)ui.issues.showModal();return issues.length===0;}
function setIssues(next){issues=next;ui.issueCount.textContent=String(issues.length);ui.issueList.innerHTML=issues.length?issues.map(x=>`<li class="issue-error">${escapeHtml(x)}</li>`).join(''):'<li class="issue-ok">エラーはありません。</li>';}
function download(){if(!validateData(true))return;const blob=new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='game.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);dirty=false;ui.saveStatus.textContent='game.jsonを書き出しました';}
async function apiRequest(url,options={}){const response=await fetch(url,{cache:'no-store',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const result=await response.json().catch(()=>({}));if(!response.ok)throw Error(result.error||`HTTP ${response.status}`);return result;}
async function loadWork(id){currentWork=id;const game=await apiRequest(`/api/works/${encodeURIComponent(id)}/game`);let source=game,label=`${id} 作品フォルダ`;try{const draft=localStorage.getItem(draftKey());if(draft){source=JSON.parse(draft);label=`${id} の未保存下書き`;dirty=true;}}catch{}loadData(source,label);if(source!==game)dirty=true;}
async function connectServer(){try{const result=await apiRequest('/api/works');serverMode=true;const select=$('work-select');select.replaceChildren();result.works.forEach(work=>{const option=document.createElement('option');option.value=work.id;option.textContent=work.title;select.append(option);});if(!result.works.length)throw Error('作品がありません');const preferred=result.works.some(w=>w.id===currentWork)?currentWork:result.works[0].id;select.value=preferred;await loadWork(preferred);return true;}catch(error){serverMode=false;$('work-select').innerHTML='<option>制作サーバー未接続</option>';$('save-work').disabled=true;$('package-work').disabled=true;ui.saveStatus.innerHTML=`<span class="server-offline">制作サーバー未接続：</span> ${escapeHtml(error.message)}`;return false;}}
async function saveWork(){if(!serverMode||!currentWork)return;if(!validateData(false)){ui.issues.showModal();return;}try{await apiRequest(`/api/works/${encodeURIComponent(currentWork)}/game`,{method:'PUT',body:JSON.stringify(data)});localStorage.removeItem(draftKey());dirty=false;ui.saveStatus.textContent=`${currentWork}/game.jsonへ保存しました（バックアップ作成済み）`;}catch(error){setIssues([`保存に失敗しました: ${error.message}`]);ui.issues.showModal();}}
async function packageCurrentWork(){if(!serverMode||!currentWork)return;if(dirty){setIssues(['公開物を生成する前に「作品へ保存」を実行してください。']);ui.issues.showModal();return;}try{const result=await apiRequest(`/api/works/${encodeURIComponent(currentWork)}/package`,{method:'POST',body:'{}'});ui.saveStatus.textContent=`公開物を生成しました：${result.output}`;}catch(error){setIssues([`公開物生成に失敗しました: ${error.message}`]);ui.issues.showModal();}}
function switchTab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.add('hidden'));$(`tab-${name}`).classList.remove('hidden');}
function bind(){ui.file.addEventListener('change',async()=>{const file=ui.file.files[0];if(!file)return;try{loadData(JSON.parse(await file.text()),file.name);}catch(error){setIssues([`JSONを読み込めません: ${error.message}`]);ui.issues.showModal();}ui.file.value='';});$('load-sample').addEventListener('click',loadSample);$('validate-button').addEventListener('click',()=>validateData(true));$('download-button').addEventListener('click',download);$('add-scene').addEventListener('click',addScene);$('move-scene-up').addEventListener('click',()=>moveScene(-1));$('move-scene-down').addEventListener('click',()=>moveScene(1));$('rename-scene').addEventListener('click',renameScene);$('delete-scene').addEventListener('click',deleteScene);$('add-command').addEventListener('click',addCommand);$('issues-button').addEventListener('click',()=>ui.issues.showModal());$('close-issues').addEventListener('click',()=>ui.issues.close());document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});}
ui.form.addEventListener('input',event=>{if(event.target.matches('input,textarea'))event.target.dispatchEvent(new Event('change'));});
$('work-select').addEventListener('change',event=>loadWork(event.target.value).catch(error=>{setIssues([`作品を読み込めません: ${error.message}`]);ui.issues.showModal();}));
$('reload-work').addEventListener('click',()=>currentWork&&loadWork(currentWork).catch(error=>{setIssues([`再読み込みに失敗しました: ${error.message}`]);ui.issues.showModal();}));
$('save-work').addEventListener('click',saveWork);
$('package-work').addEventListener('click',packageCurrentWork);
async function loadInitial(){if(await connectServer())return;try{const draft=localStorage.getItem(draftKey());if(draft){loadData(JSON.parse(draft),'未保存下書き');dirty=true;return;}}catch{}loadSample();}
$('new-work').addEventListener('click',()=>$('new-work-dialog').showModal());
$('close-new-work').addEventListener('click',()=>$('new-work-dialog').close());
$('new-work-form').addEventListener('submit',createNewWork);
$('import-script').addEventListener('click',()=>{scriptDraft=null;$('apply-script').disabled=true;$('script-errors').textContent='';$('script-preview').textContent='ここに変換結果が表示されます。';$('script-dialog').showModal();});
$('close-script').addEventListener('click',()=>$('script-dialog').close());
$('preview-script').addEventListener('click',previewScript);
$('apply-script').addEventListener('click',applyScript);
$('script-source').addEventListener('input',()=>{$('apply-script').disabled=true;scriptDraft=null;});
$('script-mode').addEventListener('change',()=>{$('apply-script').disabled=true;scriptDraft=null;});
bind();loadInitial();
}());
