import http from "node:http";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const worksRoot = path.join(projectRoot, "works");
const distRoot = path.join(projectRoot, "dist");
const host = "127.0.0.1";
const port = Number(process.env.SIMPLE_ADV_PORT || 8765);
const workIdPattern = /^[A-Za-z][A-Za-z0-9_-]*$/;
const mimeTypes = { ".html":"text/html; charset=utf-8", ".js":"text/javascript; charset=utf-8", ".mjs":"text/javascript; charset=utf-8", ".css":"text/css; charset=utf-8", ".json":"application/json; charset=utf-8", ".png":"image/png", ".jpg":"image/jpeg", ".jpeg":"image/jpeg", ".webp":"image/webp", ".mp3":"audio/mpeg", ".wav":"audio/wav", ".ogg":"audio/ogg" };

function send(res,status,body,type="application/json; charset=utf-8") { res.writeHead(status,{"Content-Type":type,"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}); res.end(Buffer.isBuffer(body)||typeof body==="string"?body:JSON.stringify(body)); }
function workPath(id,...parts) { if(!workIdPattern.test(id)) throw Object.assign(new Error("INVALID_WORK_ID"),{status:400}); const root=path.join(worksRoot,id); const target=path.resolve(root,...parts); if(target!==root&&!target.startsWith(root+path.sep)) throw Object.assign(new Error("PATH_OUTSIDE_WORK"),{status:400}); return target; }
async function readBody(req,limit=25*1024*1024) { const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>limit)throw Object.assign(new Error("BODY_TOO_LARGE"),{status:413});chunks.push(chunk);}return Buffer.concat(chunks); }
async function jsonBody(req) { try{return JSON.parse((await readBody(req)).toString("utf8"));}catch{throw Object.assign(new Error("INVALID_JSON"),{status:400});} }
async function exists(target){try{await fs.access(target);return true;}catch{return false;}}
async function listWorks(){const entries=await fs.readdir(worksRoot,{withFileTypes:true});const works=[];for(const entry of entries){if(!entry.isDirectory()||!workIdPattern.test(entry.name))continue;const gameFile=workPath(entry.name,"game.json");try{const game=JSON.parse(await fs.readFile(gameFile,"utf8"));works.push({id:entry.name,title:game.game?.title||entry.name,revision:game.game?.revision??null});}catch{works.push({id:entry.name,title:entry.name,revision:null,invalid:true});}}return works;}
async function listAssets(id){const root=workPath(id,"assets"),items=[];async function walk(dir){for(const entry of await fs.readdir(dir,{withFileTypes:true})){const full=path.join(dir,entry.name);if(entry.isDirectory())await walk(full);else items.push(path.relative(workPath(id),full).split(path.sep).join("/"));}}if(await exists(root))await walk(root);return items.sort();}
async function saveGame(id,game){if(!game||typeof game!=="object"||Array.isArray(game))throw Object.assign(new Error("INVALID_GAME_DATA"),{status:400});const target=workPath(id,"game.json"),backupDir=workPath(id,".backups");await fs.mkdir(backupDir,{recursive:true});if(await exists(target)){const stamp=new Date().toISOString().replace(/[:.]/g,"-");await fs.copyFile(target,path.join(backupDir,`${stamp}-game.json`));}await fs.writeFile(target,JSON.stringify(game,null,2)+"\n","utf8");}
async function createWork(body){const id=String(body.id||"").trim(),title=String(body.title||"").trim();if(!workIdPattern.test(id)||!title)throw Object.assign(new Error("INVALID_NEW_WORK"),{status:400});const root=workPath(id);if(await exists(root))throw Object.assign(new Error("WORK_ALREADY_EXISTS"),{status:409});const template=workPath("sansu-quest");await fs.mkdir(root,{recursive:false});try{await fs.copyFile(path.join(template,"index.html"),path.join(root,"index.html"));await fs.copyFile(path.join(template,"theme.css"),path.join(root,"theme.css"));await fs.mkdir(path.join(root,"assets"),{recursive:true});const game={formatVersion:1,game:{id,revision:1,title,startScene:"opening"},assets:{backgrounds:{},characters:{},enemies:{},bgm:{},se:{}},variables:{},scenes:{opening:[{type:"message",speaker:"",text:"ここから ものがたりが はじまります。"},{type:"end",message:"おしまい"}]}};await fs.writeFile(path.join(root,"game.json"),JSON.stringify(game,null,2)+"\n","utf8");return {id,title};}catch(error){await fs.rm(root,{recursive:true,force:true});throw error;}}
async function copyTree(source,target){await fs.mkdir(target,{recursive:true});for(const entry of await fs.readdir(source,{withFileTypes:true})){if(entry.name===".backups")continue;const from=path.join(source,entry.name),to=path.join(target,entry.name);if(entry.isDirectory())await copyTree(from,to);else await fs.copyFile(from,to);}}
async function packageWork(id){const work=workPath(id),game=JSON.parse(await fs.readFile(path.join(work,"game.json"),"utf8")),output=path.join(distRoot,id);await fs.rm(output,{recursive:true,force:true});await fs.mkdir(output,{recursive:true});for(const name of ["game.json","theme.css"]){if(await exists(path.join(work,name)))await fs.copyFile(path.join(work,name),path.join(output,name));}if(await exists(path.join(work,"assets")))await copyTree(path.join(work,"assets"),path.join(output,"assets"));for(const name of ["event-registry.js","validator.js","player.js","player.css"])await fs.copyFile(path.join(projectRoot,"engine",name),path.join(output,name));let html=await fs.readFile(path.join(work,"index.html"),"utf8");html=html.replaceAll("../../engine/player.css","player.css").replaceAll("../../engine/event-registry.js","event-registry.js").replaceAll("../../engine/validator.js","validator.js").replaceAll("../../engine/player.js","player.js");const eventFolders={multiplicationQuiz:"multiplication-quiz"};const used=[...new Set(Object.values(game.scenes||{}).flat().filter(c=>c.type==="event").map(c=>c.event))];for(const eventId of used){const folder=eventFolders[eventId];if(!folder)throw Object.assign(new Error(`UNPACKAGED_EVENT:${eventId}`),{status:400});for(const ext of ["js","css"]){const out=`event-${folder}.${ext}`;await fs.copyFile(path.join(projectRoot,"events",folder,`event.${ext}`),path.join(output,out));html=html.replaceAll(`../../events/${folder}/event.${ext}`,out);}}await fs.writeFile(path.join(output,"index.html"),html,"utf8");return path.relative(projectRoot,output).split(path.sep).join("/");}
async function api(req,res,url){const parts=url.pathname.split("/").filter(Boolean);if(req.method==="GET"&&url.pathname==="/api/status")return send(res,200,{ok:true,root:projectRoot});if(req.method==="GET"&&url.pathname==="/api/works")return send(res,200,{works:await listWorks()});if(req.method==="POST"&&url.pathname==="/api/works")return send(res,201,await createWork(await jsonBody(req)));if(parts[0]!=="api"||parts[1]!=="works"||!parts[2])return false;const id=parts[2];if(req.method==="GET"&&parts[3]==="game")return send(res,200,JSON.parse(await fs.readFile(workPath(id,"game.json"),"utf8")));if(req.method==="PUT"&&parts[3]==="game"){await saveGame(id,await jsonBody(req));return send(res,200,{ok:true,backup:true});}if(req.method==="GET"&&parts[3]==="assets")return send(res,200,{assets:await listAssets(id)});if(req.method==="POST"&&parts[3]==="assets"){const body=await jsonBody(req),relative=String(body.path||"").replaceAll("\\","/");if(!relative.startsWith("assets/")||relative.includes("..")||!body.base64)throw Object.assign(new Error("INVALID_ASSET_UPLOAD"),{status:400});const target=workPath(id,...relative.split("/"));await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,Buffer.from(body.base64,"base64"));return send(res,201,{ok:true,path:relative});}if(req.method==="POST"&&parts[3]==="package")return send(res,200,{ok:true,output:await packageWork(id)});return false;}
async function staticFile(req,res,url){if(req.method!=="GET"&&req.method!=="HEAD")return send(res,405,{error:"METHOD_NOT_ALLOWED"});let pathname=decodeURIComponent(url.pathname);if(pathname==="/")pathname="/editor/";let target=path.resolve(projectRoot,"."+pathname);if(!target.startsWith(projectRoot+path.sep)&&target!==projectRoot)return send(res,403,{error:"FORBIDDEN"});if((await fs.stat(target).catch(()=>null))?.isDirectory())target=path.join(target,"index.html");try{const body=await fs.readFile(target);send(res,200,req.method==="HEAD"?"":body,mimeTypes[path.extname(target).toLowerCase()]||"application/octet-stream");}catch{return send(res,404,{error:"NOT_FOUND"});}}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${host}:${port}`);if(url.pathname.startsWith("/api/")){if(await api(req,res,url)!==false)return;}await staticFile(req,res,url);}catch(error){send(res,error.status||500,{error:error.message||"INTERNAL_ERROR"});}});
server.listen(port,host,()=>console.log(`Simple ADV development server: http://${host}:${port}/editor/`));
